name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Debug - Show structure
        run: find . -name "package.json" -not -path "*/node_modules/*"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: "./Github Actions/02 Starting Project"

      - name: Run tests
        run: npm test
        working-directory: "./Github Actions/02 Starting Project"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: "./Github Actions/02 Starting Project"

      - name: Build project
        run: npm run build
        working-directory: "./Github Actions/02 Starting Project"

      - name: Deploy
        run: echo "Deploying ..."