name: Deploy TimesheetDB
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-and-migrate:
    name: Deploy TimesheetDB
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code,,,.
        uses: actions/checkout@v4

      - name: installing SQLCMD
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev

      - name: Add SQLCMD to pATH
        run: echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      - name: test Connection
        run: |
          sqlcmd -S "${{ vars.SQL_SERVER }},${{ vars.SQL_PORT }}" -U "${{ secrets.SQL_USERNAME }}" -P "${{ secrets.SQL_PASSWORD }}" -C -Q "SELECT @@SERVERNAME AS ServerName, @@VERSION AS Version"

      - name: deploy database table
        run: |
          sqlcmd -S "${{ vars.SQL_SERVER }},${{ vars.SQL_PORT }}" -U "${{ secrets.SQL_USERNAME }}" -P "${{ secrets.SQL_PASSWORD }}" -C -d master -i ./deploy-timesheetdb.sql

      - name: run spRunTimesheetMigration
        id: run_migration
        run: |
          RESULT=$(sqlcmd -S "${{ vars.SQL_SERVER }},${{ vars.SQL_PORT }}" -U "${{ secrets.SQL_USERNAME }}" -P "${{ secrets.SQL_PASSWORD }}" -d "${{ vars.SQL_DATABASE }}" -C -h -1 -W -Q "SET NOCOUNT ON; EXEC dbo.spRunTimesheetMigration;")
          LAST_LINE=$(echo "$RESULT" | sed '/^$/d' | tail -n 1)
          EXIT_CODE=$(echo "$LAST_LINE" | awk '{print $1}')
          STATUS=$(echo "$LAST_LINE" | awk '{$1=""; print substr($0,2)}' | sed 's/^ //')
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          if [ "$EXIT_CODE" != "0" ]; then
            echo "migration  failed (ExitCode=$EXIT_CODE)"
            exit 1
          fi

    
      - name: if it is successfull(just checking for the last time)
        if: success()
        run: echo "migration is successful"
